-- Initialize CFR Dispatch Local PostgreSQL Database Schema
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Create live_calls Table

CREATE TABLE IF NOT EXISTS public.live_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id TEXT UNIQUE NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    
    incident_type TEXT NOT NULL DEFAULT 'Unknown Incident',
    responding_units TEXT[] NOT NULL DEFAULT '{}',
    routing_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
    
    target JSONB NOT NULL DEFAULT '{
        "address": "Unknown Location",
        "subaddress": null,
        "lat": null,
        "lng": null,
        "rings": [],
        "radio_channel": null,
        "map_grid": null,
        "verified_talkgroup": null,
        "verified_map_grid": null,
        "tone_name": null,
        "include_in_training": false
    }'::jsonb,
    
    raw_transcript TEXT,
    sanitized_transcript TEXT,
    confidence_score NUMERIC(5,2) DEFAULT 0.0,
    verify_location BOOLEAN DEFAULT FALSE,
    origins TEXT[] DEFAULT '{}',
    
    audio_url TEXT,
    audio_duration NUMERIC(6,2),
    
    verified_transcript TEXT,
    verified_address TEXT,
    verified_incident TEXT,
    verified_units TEXT[],
    feedback_submitted BOOLEAN DEFAULT FALSE,
    quality_rating TEXT DEFAULT 'PENDING',
    model_updated BOOLEAN DEFAULT FALSE,
    review_notes TEXT
);

-- Indices for live_calls performance
CREATE INDEX IF NOT EXISTS idx_live_calls_timestamp ON public.live_calls (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_live_calls_target_gin ON public.live_calls USING gin (target jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_live_calls_routing_metrics_gin ON public.live_calls USING gin (routing_metrics jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_live_calls_feedback_verified ON public.live_calls (timestamp DESC) WHERE feedback_submitted = TRUE AND verified_address IS NOT NULL;
-- Note: dispatch_id automatically has a unique B-tree index via UNIQUE constraint

-- 2. Create evaluation_history Table
CREATE TABLE IF NOT EXISTS public.evaluation_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    model_version TEXT NOT NULL,
    total_samples INTEGER NOT NULL,
    wer NUMERIC(5,2) NOT NULL,
    cer NUMERIC(5,2) NOT NULL,
    perfect_percent NUMERIC(5,2) NOT NULL,
    operational_percent NUMERIC(5,2) NOT NULL,
    failed_percent NUMERIC(5,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evaluation_history_created_at ON public.evaluation_history (created_at ASC);

-- 3. Create dispatch_uploads Table
CREATE TABLE IF NOT EXISTS public.dispatch_uploads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    audio_url TEXT NOT NULL,
    verified_transcript TEXT,
    status TEXT DEFAULT 'pending' NOT NULL,
    result JSONB,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_dispatch_uploads_status ON public.dispatch_uploads (status);

-- 4. Create parcels Table (Unified 40-column master properties table)
CREATE TABLE IF NOT EXISTS public.parcels (
    -- System
    id BIGSERIAL PRIMARY KEY,
    parcel_uuid UUID DEFAULT gen_random_uuid() NOT NULL,

    -- From Addresses.shp (imported as-is)
    gis_id VARCHAR(255),                                -- Shapefile feature ID (e.g. "!2211147")
    address VARCHAR(255) NOT NULL,                      -- Full civic address (e.g. "318 Alderson Ave 2701")
    house VARCHAR(50),                                  -- House number (e.g. "318")
    street VARCHAR(255),                                -- Street name without suffix (e.g. "Alderson")
    streettype VARCHAR(50),                             -- Street suffix (e.g. "Ave", "Crt", "Dr")
    unit VARCHAR(50),                                   -- Unit/suite number (e.g. "2701")
    unittype VARCHAR(50),                               -- Unit type descriptor (e.g. "Suite", "Apt")
    postal VARCHAR(10),                                 -- Postal code (e.g. "V3K 0J1")
    block VARCHAR(50),                                  -- Block number
    plan VARCHAR(50),                                   -- Land title plan (e.g. "EPS10424")
    lot VARCHAR(50),                                    -- Lot number (e.g. "213")
    legaldesc TEXT,                                     -- Legal description (e.g. "SL 213 PID -032-268-858")
    plan_area VARCHAR(20),                              -- Plan area code (e.g. "23")
    folio VARCHAR(50),                                  -- BC Assessment folio number (e.g. "00594213")
    zonetype1 VARCHAR(30),                              -- Primary municipal zoning (e.g. "RS-1", "RM-6", "C-7")
    zonetype2 VARCHAR(30),                              -- Secondary municipal zoning
    zonetype3 VARCHAR(30),                              -- Tertiary municipal zoning
    status VARCHAR(20),                                 -- Address status ("Active")
    units INTEGER,                                      -- Total unit count for building (e.g. 383)
    sc_card VARCHAR(50),                                -- Safety card reference
    extract_dt DATE,                                    -- Shapefile extract date

    -- From Addresses.shp geometry
    lat DOUBLE PRECISION,                               -- Latitude from shapefile point geometry
    lng DOUBLE PRECISION,                               -- Longitude from shapefile point geometry

    -- Pre-computed at import (spatial intersection with Emergency_Response_Zones.shp)
    zone_id VARCHAR(16),                                -- Emergency response zone (1–134)

    -- Computed at import
    address_normalized VARCHAR(255),                    -- Lowercase canonical address for fuzzy matching

    -- Operational (populated by firefighters / admin tools)
    front_lat DOUBLE PRECISION,                         -- Frontage point lat (Street View anchor)
    front_lng DOUBLE PRECISION,                         -- Frontage point lng
    centroid_lat DOUBLE PRECISION,                      -- True geometric centroid lat
    centroid_lng DOUBLE PRECISION,                      -- True geometric centroid lng
    entrance_lat DOUBLE PRECISION,                      -- Building entrance lat
    entrance_lng DOUBLE PRECISION,                      -- Building entrance lng
    streetview_heading DOUBLE PRECISION DEFAULT 0.0,    -- Street View camera heading (degrees)
    streetview_pitch DOUBLE PRECISION DEFAULT 5.0,      -- Street View camera pitch
    streetview_fov DOUBLE PRECISION DEFAULT 80.0,       -- Street View camera field of view
    lock_box_notes TEXT,                                -- Key box / lock box location
    hazard_notes TEXT,                                  -- Hazmat, safety warnings
    pre_plan_pdf_url TEXT,                              -- Pre-incident plan document URL
    construction_type VARCHAR(100),                     -- Building construction class
    floor_count INTEGER,                                -- Number of floors
    is_pa_page BOOLEAN NOT NULL DEFAULT FALSE,          -- PA page flag

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Primary lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_parcels_address ON public.parcels (address);
CREATE INDEX IF NOT EXISTS idx_parcels_address_normalized ON public.parcels (address_normalized);
CREATE INDEX IF NOT EXISTS idx_parcels_gis_id ON public.parcels (gis_id);

-- Dispatch-critical lookups
CREATE INDEX IF NOT EXISTS idx_parcels_zone_id ON public.parcels (zone_id);
CREATE INDEX IF NOT EXISTS idx_parcels_street ON public.parcels (street, streettype);
CREATE INDEX IF NOT EXISTS idx_parcels_house_street ON public.parcels (house, street);

-- Unit queries (filter building vs unit at query time)
CREATE INDEX IF NOT EXISTS idx_parcels_unit ON public.parcels (unit) WHERE unit IS NOT NULL AND unit != '';

-- Municipal zoning
CREATE INDEX IF NOT EXISTS idx_parcels_zonetype1 ON public.parcels (zonetype1);

