-- Initialize CFR Dispatch Local PostgreSQL Database Schema
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Create live_calls Table

CREATE TABLE IF NOT EXISTS public.live_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id TEXT UNIQUE NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    
    incident_type TEXT NOT NULL DEFAULT 'Unknown Incident',
    responding_units TEXT[] NOT NULL DEFAULT '{}',
    routing_metrics JSONB NOT NULL DEFAULT '[]'::jsonb,
    
    target JSONB NOT NULL DEFAULT '{
        "address": "Unknown Location",
        "subaddress": null,
        "lat": null,
        "lng": null,
        "rings": [],
        "radio_channel": null,
        "map_grid": null,
        "verified_talkgroup": null,
        "verified_map_grid": null,
        "tone_name": null,
        "include_in_training": false
    }'::jsonb,
    
    raw_transcript TEXT,
    sanitized_transcript TEXT,
    confidence_score NUMERIC(5,2) DEFAULT 0.0,
    verify_location BOOLEAN DEFAULT FALSE,
    origins TEXT[] DEFAULT '{}',
    
    audio_url TEXT,
    audio_duration NUMERIC(6,2),
    
    verified_transcript TEXT,
    verified_address TEXT,
    verified_incident TEXT,
    verified_units TEXT[],
    feedback_submitted BOOLEAN DEFAULT FALSE,
    quality_rating TEXT DEFAULT 'PENDING',
    model_updated BOOLEAN DEFAULT FALSE,
    review_notes TEXT
);

-- Indices for live_calls performance
CREATE INDEX IF NOT EXISTS idx_live_calls_timestamp ON public.live_calls (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_live_calls_target_gin ON public.live_calls USING gin (target jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_live_calls_routing_metrics_gin ON public.live_calls USING gin (routing_metrics jsonb_path_ops);
CREATE INDEX IF NOT EXISTS idx_live_calls_feedback_verified ON public.live_calls (timestamp DESC) WHERE feedback_submitted = TRUE AND verified_address IS NOT NULL;
-- Note: dispatch_id automatically has a unique B-tree index via UNIQUE constraint

-- 2. Create evaluation_history Table
CREATE TABLE IF NOT EXISTS public.evaluation_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    model_version TEXT NOT NULL,
    total_samples INTEGER NOT NULL,
    wer NUMERIC(5,2) NOT NULL,
    cer NUMERIC(5,2) NOT NULL,
    perfect_percent NUMERIC(5,2) NOT NULL,
    operational_percent NUMERIC(5,2) NOT NULL,
    failed_percent NUMERIC(5,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evaluation_history_created_at ON public.evaluation_history (created_at ASC);

-- 3. Create dispatch_uploads Table
CREATE TABLE IF NOT EXISTS public.dispatch_uploads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    audio_url TEXT NOT NULL,
    verified_transcript TEXT,
    status TEXT DEFAULT 'pending' NOT NULL,
    result JSONB,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_dispatch_uploads_status ON public.dispatch_uploads (status);

-- 4. Create parcels Table
CREATE TABLE IF NOT EXISTS public.parcels (
    id SERIAL PRIMARY KEY,
    gis_id VARCHAR(255),
    clean_address VARCHAR(255) UNIQUE NOT NULL,
    full_address VARCHAR(255),
    street_number VARCHAR(50),
    street_name VARCHAR(255),
    municipality VARCHAR(100),
    zone_id VARCHAR(16),
    geometry JSONB,
    parcel_lat DOUBLE PRECISION,
    parcel_lng DOUBLE PRECISION,
    front_lat DOUBLE PRECISION,
    front_lng DOUBLE PRECISION,
    centroid_lat DOUBLE PRECISION,
    centroid_lng DOUBLE PRECISION,
    entrance_lat DOUBLE PRECISION,
    entrance_lng DOUBLE PRECISION,
    streetview_heading DOUBLE PRECISION DEFAULT 0.0,
    streetview_pitch DOUBLE PRECISION DEFAULT 5.0,
    streetview_fov DOUBLE PRECISION DEFAULT 80.0,
    lock_box_notes TEXT,
    hazard_notes TEXT,
    pre_plan_pdf_url TEXT,
    construction_type VARCHAR(100),
    floor_count INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_parcels_clean_address ON public.parcels (clean_address);

-- 5. Create streetview_overrides Table (legacy)
CREATE TABLE IF NOT EXISTS public.streetview_overrides (
    id SERIAL PRIMARY KEY,
    clean_address VARCHAR(255) UNIQUE NOT NULL,
    front_lat DOUBLE PRECISION NOT NULL,
    front_lng DOUBLE PRECISION NOT NULL,
    heading DOUBLE PRECISION DEFAULT 0.0,
    pitch DOUBLE PRECISION DEFAULT 5.0,
    fov DOUBLE PRECISION DEFAULT 80.0,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_streetview_overrides_clean_address ON public.streetview_overrides (clean_address);

