-- Initialize CFR Dispatch Local PostgreSQL Database Schema

-- 1. Create live_calls Table
CREATE TABLE IF NOT EXISTS public.live_calls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id TEXT UNIQUE NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    
    incident_type TEXT NOT NULL DEFAULT 'Unknown Incident',
    responding_units TEXT[] NOT NULL DEFAULT '{}',
    
    target JSONB NOT NULL DEFAULT '{
        "address": "Unknown Location",
        "subaddress": null,
        "lat": null,
        "lng": null,
        "rings": [],
        "radio_channel": null,
        "map_grid": null,
        "verified_talkgroup": null,
        "verified_map_grid": null,
        "tone_name": null,
        "include_in_training": false
    }'::jsonb,
    
    raw_transcript TEXT,
    sanitized_transcript TEXT,
    confidence_score NUMERIC(5,2) DEFAULT 0.0,
    verify_location BOOLEAN DEFAULT FALSE,
    origins TEXT[] DEFAULT '{}',
    
    audio_url TEXT,
    audio_duration NUMERIC(6,2),
    
    verified_transcript TEXT,
    verified_address TEXT,
    verified_incident TEXT,
    verified_units TEXT[],
    feedback_submitted BOOLEAN DEFAULT FALSE,
    quality_rating TEXT DEFAULT 'PENDING',
    model_updated BOOLEAN DEFAULT FALSE,
    review_notes TEXT
);

-- Indices for live_calls performance
CREATE INDEX IF NOT EXISTS idx_live_calls_timestamp ON public.live_calls (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_live_calls_feedback ON public.live_calls (feedback_submitted, verify_location);
CREATE INDEX IF NOT EXISTS idx_live_calls_dispatch_id ON public.live_calls (dispatch_id);

-- 2. Create evaluation_history Table
CREATE TABLE IF NOT EXISTS public.evaluation_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    model_version TEXT NOT NULL,
    total_samples INTEGER NOT NULL,
    wer NUMERIC(5,2) NOT NULL,
    cer NUMERIC(5,2) NOT NULL,
    perfect_percent NUMERIC(5,2) NOT NULL,
    operational_percent NUMERIC(5,2) NOT NULL,
    failed_percent NUMERIC(5,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evaluation_history_created_at ON public.evaluation_history (created_at ASC);

-- 3. Create dispatch_uploads Table
CREATE TABLE IF NOT EXISTS public.dispatch_uploads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    audio_url TEXT NOT NULL,
    verified_transcript TEXT,
    status TEXT DEFAULT 'pending' NOT NULL,
    result JSONB,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_dispatch_uploads_status ON public.dispatch_uploads (status);
