-- Vocabulary seed: public.vocabulary is the sole source of truth
--
-- PROVENANCE (CLAUDE.md §6.3, tier 4 - department operational policy):
-- These terms are curated by Coquitlam Fire Rescue (Curtis Woodworth), derived from
-- department SOGs combined with operational knowledge of what the Locution digital
-- dispatch system actually announces over the air.
--
-- The SOG alone is NOT a sufficient source. SOGs list CAD codes (e.g. "MVI4"), while
-- the spoken announcement uses a different, more specific phrasing (e.g. "Motor Vehicle
-- Incident - Roll Over"). The parser matches the spoken form, so this table is the only
-- record of that mapping. The department does not hold the Locution call-type list.
--
-- This replaces the .txt files under backend/data/vocabulary/, which were previously
-- both the seed and a silent runtime fallback. Terms are added by INSERT here or, for
-- terms discovered from real calls, automatically with source='hitl_learned' by
-- backend/scripts/extract_training_data.py.
--
-- Idempotent: ON CONFLICT DO NOTHING against the (category, term) unique index.

BEGIN;

INSERT INTO public.vocabulary (category, term, term_normalized, sort_order, source, is_active)
VALUES
    ('call_type', 'Electrical Problem', 'electrical problem', 1, 'cfr_curated', TRUE),
    ('call_type', 'Alarm Activated - High Risk', 'alarm activated - high risk', 2, 'cfr_curated', TRUE),
    ('call_type', 'Alarm Activated', 'alarm activated', 3, 'cfr_curated', TRUE),
    ('call_type', 'Alarms Activated - High Risk', 'alarms activated - high risk', 4, 'cfr_curated', TRUE),
    ('call_type', 'Alarms Activated', 'alarms activated', 5, 'cfr_curated', TRUE),
    ('call_type', 'Structure Fire - High Risk', 'structure fire - high risk', 6, 'cfr_curated', TRUE),
    ('call_type', 'Structure Fire', 'structure fire', 7, 'cfr_curated', TRUE),
    ('call_type', 'Vehicle Fire - Large Vehicle', 'vehicle fire - large vehicle', 8, 'cfr_curated', TRUE),
    ('call_type', 'Vehicle Fire', 'vehicle fire', 9, 'cfr_curated', TRUE),
    ('call_type', 'Wildland Fire - Smouldering', 'wildland fire - smouldering', 10, 'cfr_curated', TRUE),
    ('call_type', 'Wildland Fire - Smoldering', 'wildland fire - smoldering', 11, 'cfr_curated', TRUE),
    ('call_type', 'Wildland Fire - Small Area', 'wildland fire - small area', 12, 'cfr_curated', TRUE),
    ('call_type', 'Wildland Fire', 'wildland fire', 13, 'cfr_curated', TRUE),
    ('call_type', 'Rubbish Fire', 'rubbish fire', 14, 'cfr_curated', TRUE),
    ('call_type', 'Tent Fire', 'tent fire', 15, 'cfr_curated', TRUE),
    ('call_type', 'Gas Leak', 'gas leak', 16, 'cfr_curated', TRUE),
    ('call_type', 'Wires Down', 'wires down', 17, 'cfr_curated', TRUE),
    ('call_type', 'Hazmat 1', 'hazmat 1', 18, 'cfr_curated', TRUE),
    ('call_type', 'Hazmat 2', 'hazmat 2', 19, 'cfr_curated', TRUE),
    ('call_type', 'Hazmat 3', 'hazmat 3', 20, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Significant Event - Multiple Patients', 'medical aid - significant event - multiple patients', 21, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Allergic Reaction', 'medical aid - allergic reaction', 22, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Abdominal Pain', 'medical aid - abdominal pain', 23, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Cardiac Arrest', 'medical aid - cardiac arrest', 24, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Cardiac Problems', 'medical aid - cardiac problems', 25, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Cardiac Problem', 'medical aid - cardiac problem', 26, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Chest Pain', 'medical aid - chest pain', 27, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Collapse', 'medical aid - collapse', 28, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Difficulty Breathing', 'medical aid - difficulty breathing', 29, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Breathing Problems', 'medical aid - breathing problems', 30, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Breathing Problem', 'medical aid - breathing problem', 31, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Diabetic', 'medical aid - diabetic', 32, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Fall', 'medical aid - fall', 33, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Hemorrhage', 'medical aid - hemorrhage', 34, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Maternity', 'medical aid - maternity', 35, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Overdose', 'medical aid - overdose', 36, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Seizure', 'medical aid - seizure', 37, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Stroke', 'medical aid - stroke', 38, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Traumatic Injuries', 'medical aid - traumatic injuries', 39, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Assault', 'medical aid - assault', 40, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Back Pain', 'medical aid - back pain', 41, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Assist', 'medical aid - assist', 42, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - General Illness', 'medical aid - general illness', 43, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid', 'medical aid', 44, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident - Large Vehicle', 'motor vehicle incident - large vehicle', 45, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident - Rollover', 'motor vehicle incident - rollover', 46, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident - Skytrain', 'motor vehicle incident - skytrain', 47, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident - High Velocity Impact', 'motor vehicle incident - high velocity impact', 48, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident - Pedestrian Struck', 'motor vehicle incident - pedestrian struck', 49, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident - Cyclist Struck', 'motor vehicle incident - cyclist struck', 50, 'cfr_curated', TRUE),
    ('call_type', 'Motor Vehicle Incident', 'motor vehicle incident', 51, 'cfr_curated', TRUE),
    ('call_type', 'Vehicle Rollover', 'vehicle rollover', 52, 'cfr_curated', TRUE),
    ('call_type', 'Public Assist', 'public assist', 53, 'cfr_curated', TRUE),
    ('call_type', 'Lift Assist', 'lift assist', 54, 'cfr_curated', TRUE),
    ('call_type', 'Rescue', 'rescue', 55, 'cfr_curated', TRUE),
    ('call_type', 'Confined Space Rescue', 'confined space rescue', 56, 'cfr_curated', TRUE),
    ('call_type', 'Rope Rescue', 'rope rescue', 57, 'cfr_curated', TRUE),
    ('call_type', 'Swift Water Rescue', 'swift water rescue', 58, 'cfr_curated', TRUE),
    ('call_type', 'Technical Rescue', 'technical rescue', 59, 'cfr_curated', TRUE),
    ('call_type', 'Report of Smoke - High Risk', 'report of smoke - high risk', 60, 'cfr_curated', TRUE),
    ('call_type', 'Report of Smoke - Indoors', 'report of smoke - indoors', 61, 'cfr_curated', TRUE),
    ('call_type', 'Report of Smoke', 'report of smoke', 62, 'cfr_curated', TRUE),
    ('call_type', 'Testing Only', 'testing only', 63, 'cfr_curated', TRUE),
    ('call_type', 'Burning Complaint', 'burning complaint', 64, 'cfr_curated', TRUE),
    ('call_type', 'Compressed Gas Smell - Inside', 'compressed gas smell - inside', 65, 'cfr_curated', TRUE),
    ('call_type', 'Medical Aid - Headache', 'medical aid - headache', 66, 'cfr_curated', TRUE),
    ('map_grid', '1', '1', 1, 'cfr_curated', TRUE),
    ('map_grid', '2', '2', 2, 'cfr_curated', TRUE),
    ('map_grid', '3', '3', 3, 'cfr_curated', TRUE),
    ('map_grid', '4', '4', 4, 'cfr_curated', TRUE),
    ('map_grid', '5', '5', 5, 'cfr_curated', TRUE),
    ('map_grid', '6', '6', 6, 'cfr_curated', TRUE),
    ('map_grid', '7', '7', 7, 'cfr_curated', TRUE),
    ('map_grid', '8', '8', 8, 'cfr_curated', TRUE),
    ('map_grid', '9', '9', 9, 'cfr_curated', TRUE),
    ('map_grid', '10', '10', 10, 'cfr_curated', TRUE),
    ('map_grid', '11', '11', 11, 'cfr_curated', TRUE),
    ('map_grid', '12', '12', 12, 'cfr_curated', TRUE),
    ('map_grid', '13', '13', 13, 'cfr_curated', TRUE),
    ('map_grid', '14', '14', 14, 'cfr_curated', TRUE),
    ('map_grid', '15', '15', 15, 'cfr_curated', TRUE),
    ('map_grid', '16', '16', 16, 'cfr_curated', TRUE),
    ('map_grid', '17', '17', 17, 'cfr_curated', TRUE),
    ('map_grid', '18', '18', 18, 'cfr_curated', TRUE),
    ('map_grid', '19', '19', 19, 'cfr_curated', TRUE),
    ('map_grid', '20', '20', 20, 'cfr_curated', TRUE),
    ('map_grid', '21', '21', 21, 'cfr_curated', TRUE),
    ('map_grid', '22', '22', 22, 'cfr_curated', TRUE),
    ('map_grid', '23', '23', 23, 'cfr_curated', TRUE),
    ('map_grid', '24', '24', 24, 'cfr_curated', TRUE),
    ('map_grid', '25', '25', 25, 'cfr_curated', TRUE),
    ('map_grid', '26', '26', 26, 'cfr_curated', TRUE),
    ('map_grid', '27', '27', 27, 'cfr_curated', TRUE),
    ('map_grid', '28', '28', 28, 'cfr_curated', TRUE),
    ('map_grid', '29', '29', 29, 'cfr_curated', TRUE),
    ('map_grid', '30', '30', 30, 'cfr_curated', TRUE),
    ('map_grid', '31', '31', 31, 'cfr_curated', TRUE),
    ('map_grid', '32', '32', 32, 'cfr_curated', TRUE),
    ('map_grid', '33', '33', 33, 'cfr_curated', TRUE),
    ('map_grid', '34', '34', 34, 'cfr_curated', TRUE),
    ('map_grid', '35', '35', 35, 'cfr_curated', TRUE),
    ('map_grid', '36', '36', 36, 'cfr_curated', TRUE),
    ('map_grid', '37', '37', 37, 'cfr_curated', TRUE),
    ('map_grid', '38', '38', 38, 'cfr_curated', TRUE),
    ('map_grid', '39', '39', 39, 'cfr_curated', TRUE),
    ('map_grid', '40', '40', 40, 'cfr_curated', TRUE),
    ('map_grid', '41', '41', 41, 'cfr_curated', TRUE),
    ('map_grid', '42', '42', 42, 'cfr_curated', TRUE),
    ('map_grid', '43', '43', 43, 'cfr_curated', TRUE),
    ('map_grid', '44', '44', 44, 'cfr_curated', TRUE),
    ('map_grid', '45', '45', 45, 'cfr_curated', TRUE),
    ('map_grid', '46', '46', 46, 'cfr_curated', TRUE),
    ('map_grid', '47', '47', 47, 'cfr_curated', TRUE),
    ('map_grid', '48', '48', 48, 'cfr_curated', TRUE),
    ('map_grid', '49', '49', 49, 'cfr_curated', TRUE),
    ('map_grid', '50', '50', 50, 'cfr_curated', TRUE),
    ('map_grid', '51', '51', 51, 'cfr_curated', TRUE),
    ('map_grid', '52', '52', 52, 'cfr_curated', TRUE),
    ('map_grid', '53', '53', 53, 'cfr_curated', TRUE),
    ('map_grid', '54', '54', 54, 'cfr_curated', TRUE),
    ('map_grid', '55', '55', 55, 'cfr_curated', TRUE),
    ('map_grid', '56', '56', 56, 'cfr_curated', TRUE),
    ('map_grid', '57', '57', 57, 'cfr_curated', TRUE),
    ('map_grid', '58', '58', 58, 'cfr_curated', TRUE),
    ('map_grid', '59', '59', 59, 'cfr_curated', TRUE),
    ('map_grid', '60', '60', 60, 'cfr_curated', TRUE),
    ('map_grid', '61', '61', 61, 'cfr_curated', TRUE),
    ('map_grid', '62', '62', 62, 'cfr_curated', TRUE),
    ('map_grid', '63', '63', 63, 'cfr_curated', TRUE),
    ('map_grid', '64', '64', 64, 'cfr_curated', TRUE),
    ('map_grid', '65', '65', 65, 'cfr_curated', TRUE),
    ('map_grid', '66', '66', 66, 'cfr_curated', TRUE),
    ('map_grid', '67', '67', 67, 'cfr_curated', TRUE),
    ('map_grid', '68', '68', 68, 'cfr_curated', TRUE),
    ('map_grid', '69', '69', 69, 'cfr_curated', TRUE),
    ('map_grid', '70', '70', 70, 'cfr_curated', TRUE),
    ('map_grid', '71', '71', 71, 'cfr_curated', TRUE),
    ('map_grid', '72', '72', 72, 'cfr_curated', TRUE),
    ('map_grid', '73', '73', 73, 'cfr_curated', TRUE),
    ('map_grid', '74', '74', 74, 'cfr_curated', TRUE),
    ('map_grid', '75', '75', 75, 'cfr_curated', TRUE),
    ('map_grid', '76', '76', 76, 'cfr_curated', TRUE),
    ('map_grid', '77', '77', 77, 'cfr_curated', TRUE),
    ('map_grid', '78', '78', 78, 'cfr_curated', TRUE),
    ('map_grid', '79', '79', 79, 'cfr_curated', TRUE),
    ('map_grid', '80', '80', 80, 'cfr_curated', TRUE),
    ('map_grid', '81', '81', 81, 'cfr_curated', TRUE),
    ('map_grid', '82', '82', 82, 'cfr_curated', TRUE),
    ('map_grid', '83', '83', 83, 'cfr_curated', TRUE),
    ('map_grid', '84', '84', 84, 'cfr_curated', TRUE),
    ('map_grid', '85', '85', 85, 'cfr_curated', TRUE),
    ('map_grid', '86', '86', 86, 'cfr_curated', TRUE),
    ('map_grid', '87', '87', 87, 'cfr_curated', TRUE),
    ('map_grid', '88', '88', 88, 'cfr_curated', TRUE),
    ('map_grid', '89', '89', 89, 'cfr_curated', TRUE),
    ('map_grid', '90', '90', 90, 'cfr_curated', TRUE),
    ('map_grid', '91', '91', 91, 'cfr_curated', TRUE),
    ('map_grid', '92', '92', 92, 'cfr_curated', TRUE),
    ('map_grid', '93', '93', 93, 'cfr_curated', TRUE),
    ('map_grid', '94', '94', 94, 'cfr_curated', TRUE),
    ('map_grid', '95', '95', 95, 'cfr_curated', TRUE),
    ('map_grid', '96', '96', 96, 'cfr_curated', TRUE),
    ('map_grid', '97', '97', 97, 'cfr_curated', TRUE),
    ('map_grid', '98', '98', 98, 'cfr_curated', TRUE),
    ('map_grid', '99', '99', 99, 'cfr_curated', TRUE),
    ('map_grid', '100', '100', 100, 'cfr_curated', TRUE),
    ('map_grid', '101', '101', 101, 'cfr_curated', TRUE),
    ('map_grid', '102', '102', 102, 'cfr_curated', TRUE),
    ('map_grid', '103', '103', 103, 'cfr_curated', TRUE),
    ('map_grid', '104', '104', 104, 'cfr_curated', TRUE),
    ('map_grid', '105', '105', 105, 'cfr_curated', TRUE),
    ('map_grid', '106', '106', 106, 'cfr_curated', TRUE),
    ('map_grid', '107', '107', 107, 'cfr_curated', TRUE),
    ('map_grid', '108', '108', 108, 'cfr_curated', TRUE),
    ('map_grid', '109', '109', 109, 'cfr_curated', TRUE),
    ('map_grid', '110', '110', 110, 'cfr_curated', TRUE),
    ('map_grid', '111', '111', 111, 'cfr_curated', TRUE),
    ('map_grid', '112', '112', 112, 'cfr_curated', TRUE),
    ('map_grid', '113', '113', 113, 'cfr_curated', TRUE),
    ('map_grid', '114', '114', 114, 'cfr_curated', TRUE),
    ('map_grid', '115', '115', 115, 'cfr_curated', TRUE),
    ('map_grid', '116', '116', 116, 'cfr_curated', TRUE),
    ('map_grid', '117', '117', 117, 'cfr_curated', TRUE),
    ('map_grid', '118', '118', 118, 'cfr_curated', TRUE),
    ('map_grid', '119', '119', 119, 'cfr_curated', TRUE),
    ('map_grid', '120', '120', 120, 'cfr_curated', TRUE),
    ('map_grid', '121', '121', 121, 'cfr_curated', TRUE),
    ('map_grid', '122', '122', 122, 'cfr_curated', TRUE),
    ('map_grid', '123', '123', 123, 'cfr_curated', TRUE),
    ('map_grid', '124', '124', 124, 'cfr_curated', TRUE),
    ('map_grid', '125', '125', 125, 'cfr_curated', TRUE),
    ('map_grid', '126', '126', 126, 'cfr_curated', TRUE),
    ('map_grid', '127', '127', 127, 'cfr_curated', TRUE),
    ('map_grid', '128', '128', 128, 'cfr_curated', TRUE),
    ('map_grid', '129', '129', 129, 'cfr_curated', TRUE),
    ('map_grid', '130', '130', 130, 'cfr_curated', TRUE),
    ('map_grid', '131', '131', 131, 'cfr_curated', TRUE),
    ('map_grid', '132', '132', 132, 'cfr_curated', TRUE),
    ('map_grid', '133', '133', 133, 'cfr_curated', TRUE),
    ('map_grid', '134', '134', 134, 'cfr_curated', TRUE),
    ('radio_channel', 'Talk Group 5 Coquitlam', 'talk group 5 coquitlam', 1, 'cfr_curated', TRUE),
    ('radio_channel', 'Talk Group 6 Coquitlam', 'talk group 6 coquitlam', 2, 'cfr_curated', TRUE),
    ('radio_channel', 'Talk Group 7 Coquitlam', 'talk group 7 coquitlam', 3, 'cfr_curated', TRUE),
    ('radio_channel', 'Talk Group 8 Coquitlam', 'talk group 8 coquitlam', 4, 'cfr_curated', TRUE),
    ('radio_channel', 'Talk Group 9 Coquitlam', 'talk group 9 coquitlam', 5, 'cfr_curated', TRUE),
    ('radio_channel', 'Talk Group 10 Combined Response Coquitlam', 'talk group 10 combined response coquitlam', 6, 'cfr_curated', TRUE),
    ('radio_channel', 'Combined Venue Port Mann', 'combined venue port mann', 7, 'cfr_curated', TRUE),
    ('radio_channel', 'Combined Venue Transit System', 'combined venue transit system', 8, 'cfr_curated', TRUE),
    ('response_type', 'routine', 'routine', 1, 'cfr_curated', TRUE),
    ('response_type', 'emergency', 'emergency', 2, 'cfr_curated', TRUE),
    ('unit', 'Engine 1', 'engine 1', 1, 'cfr_curated', TRUE),
    ('unit', 'Engine 2', 'engine 2', 2, 'cfr_curated', TRUE),
    ('unit', 'Engine 3', 'engine 3', 3, 'cfr_curated', TRUE),
    ('unit', 'Engine 4', 'engine 4', 4, 'cfr_curated', TRUE),
    ('unit', 'Engine 5', 'engine 5', 5, 'cfr_curated', TRUE),
    ('unit', 'Engine 10', 'engine 10', 6, 'cfr_curated', TRUE),
    ('unit', 'Engine 11', 'engine 11', 7, 'cfr_curated', TRUE),
    ('unit', 'Ladder 1', 'ladder 1', 8, 'cfr_curated', TRUE),
    ('unit', 'Ladder 2', 'ladder 2', 9, 'cfr_curated', TRUE),
    ('unit', 'Ladder 3', 'ladder 3', 10, 'cfr_curated', TRUE),
    ('unit', 'Ladder 4', 'ladder 4', 11, 'cfr_curated', TRUE),
    ('unit', 'Medic 1', 'medic 1', 12, 'cfr_curated', TRUE),
    ('unit', 'Medic 2', 'medic 2', 13, 'cfr_curated', TRUE),
    ('unit', 'Medic 3', 'medic 3', 14, 'cfr_curated', TRUE),
    ('unit', 'Medic 4', 'medic 4', 15, 'cfr_curated', TRUE),
    ('unit', 'Rescue 1', 'rescue 1', 16, 'cfr_curated', TRUE),
    ('unit', 'Rescue 2', 'rescue 2', 17, 'cfr_curated', TRUE),
    ('unit', 'Rescue 3', 'rescue 3', 18, 'cfr_curated', TRUE),
    ('unit', 'Rescue 4', 'rescue 4', 19, 'cfr_curated', TRUE),
    ('unit', 'Quint 5', 'quint 5', 20, 'cfr_curated', TRUE),
    ('unit', 'Squad 1', 'squad 1', 21, 'cfr_curated', TRUE),
    ('unit', 'Squad 2', 'squad 2', 22, 'cfr_curated', TRUE),
    ('unit', 'Squad 3', 'squad 3', 23, 'cfr_curated', TRUE),
    ('unit', 'Squad 4', 'squad 4', 24, 'cfr_curated', TRUE),
    ('unit', 'Tender 1', 'tender 1', 25, 'cfr_curated', TRUE),
    ('unit', 'Tender 2', 'tender 2', 26, 'cfr_curated', TRUE),
    ('unit', 'Tender 4', 'tender 4', 27, 'cfr_curated', TRUE),
    ('unit', 'Water Tender 1', 'water tender 1', 28, 'cfr_curated', TRUE),
    ('unit', 'Water Tender 2', 'water tender 2', 29, 'cfr_curated', TRUE),
    ('unit', 'Water Tender 4', 'water tender 4', 30, 'cfr_curated', TRUE),
    ('unit', 'Hazmat 3', 'hazmat 3', 31, 'cfr_curated', TRUE),
    ('unit', 'Hazmat Tender 3', 'hazmat tender 3', 32, 'cfr_curated', TRUE),
    ('unit', 'Light Attack Vehicle 4', 'light attack vehicle 4', 33, 'cfr_curated', TRUE),
    ('unit', 'Battalion 1', 'battalion 1', 34, 'cfr_curated', TRUE),
    ('unit', 'Battalion 2', 'battalion 2', 35, 'cfr_curated', TRUE),
    ('unit', 'Chief 1', 'chief 1', 36, 'cfr_curated', TRUE),
    ('unit', 'Chief 2', 'chief 2', 37, 'cfr_curated', TRUE),
    ('unit', 'Car 1', 'car 1', 38, 'cfr_curated', TRUE),
    ('unit', 'Car 2', 'car 2', 39, 'cfr_curated', TRUE),
    ('unit', 'Car 3', 'car 3', 40, 'cfr_curated', TRUE),
    ('unit', 'Car 4', 'car 4', 41, 'cfr_curated', TRUE),
    ('unit', 'Car 5', 'car 5', 42, 'cfr_curated', TRUE),
    ('unit', 'Car 6', 'car 6', 43, 'cfr_curated', TRUE),
    ('unit', 'Car 7', 'car 7', 44, 'cfr_curated', TRUE),
    ('unit', 'Car 8', 'car 8', 45, 'cfr_curated', TRUE),
    ('unit', 'Car 9', 'car 9', 46, 'cfr_curated', TRUE)
ON CONFLICT (category, term) DO NOTHING;

-- Existing rows keep their data; only re-stamp the seed provenance.
UPDATE public.vocabulary
   SET source = 'cfr_curated'
 WHERE source = 'import';

COMMIT;
