// The self-hosted street basemap: vector tiles from the OSM extract the kiosk routes on,
// drawn by MapLibre GL under the Leaflet overlays. The style is the committed artefact
// frontend/public/basemap/street.style.json, generated by tools/build_basemap_style.py from
// the vendored OSM Bright style with the operator's rulings of 2026-09-09; this module fills
// its two placeholders at load time and knows which of its layers the app toggles.
//
// Licences and the credit line: docs/standards/basemap/README.md.
import { TILE_BASE_URL } from '../../apiClient';

/** The archive's service name on cfr_tiles: backend/data/tiles/street_vector.mbtiles. */
export const STREET_VECTOR_SERVICE = 'street_vector';

/** Where the style, sprite and glyphs are served: this app's own origin (CLAUDE.md s1: an
 *  absolute URL, never a relative path; the assets are part of the built frontend). */
export function basemapAssetsUrl() {
  const base = (import.meta.env.BASE_URL || '/').replace(/\/$/, '');
  return `${window.location.origin}${base}/basemap`;
}

/**
 * Fetch the style and the tileset's TileJSON, fill the placeholders, and add the coverage
 * fill: the style has no background layer, so the land colour is painted only over the
 * bounds the tileset itself declares and the "no map data" hatch on .leaflet-container
 * shows everywhere else (punch-list #40; CLAUDE.md s6.1 -- nothing paints ground where
 * there is no data). A failed fetch rejects; the caller leaves the hatch showing.
 */
export async function loadStreetStyle() {
  const assets = basemapAssetsUrl();
  const tilejsonUrl = `${TILE_BASE_URL}/services/${STREET_VECTOR_SERVICE}`;
  const [text, tilejson] = await Promise.all([
    fetch(`${assets}/street.style.json`).then((r) => {
      if (!r.ok) throw new Error(`street style: HTTP ${r.status}`);
      return r.text();
    }),
    fetch(tilejsonUrl).then((r) => {
      if (!r.ok) throw new Error(`tileset ${STREET_VECTOR_SERVICE}: HTTP ${r.status}`);
      return r.json();
    }),
  ]);
  const style = JSON.parse(
    text.split('{{TILEJSON_URL}}').join(tilejsonUrl).split('{{ASSETS_URL}}').join(assets),
  );
  const bounds = Array.isArray(tilejson.bounds) && tilejson.bounds.length === 4 ? tilejson.bounds : null;
  if (bounds) {
    const [w, s, e, n] = bounds;
    style.sources.coverage = {
      type: 'geojson',
      data: { type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [[[w, s], [e, s], [e, n], [w, n], [w, s]]] } },
    };
    style.layers.unshift({
      id: 'coverage', type: 'fill', source: 'coverage',
      paint: { 'fill-color': (style.metadata && style.metadata['cfr:background']) || '#f8f4f0' },
    });
  }
  return style;
}

/** Layer ids the style's metadata names, or an empty list if the style has none. */
function metaList(style, key) {
  const v = style && style.metadata && style.metadata[key];
  return Array.isArray(v) ? v : [];
}

/**
 * Show or hide every label the operator left on. `false` is the old "_nolabels" meaning of
 * the raster layer: no names at all, not even the ones the style keeps.
 */
export function setLabelsVisible(glMap, visible) {
  const style = glMap.getStyle();
  for (const id of metaList(style, 'cfr:labels-on')) {
    if (glMap.getLayer(id)) glMap.setLayoutProperty(id, 'visibility', visible ? 'visible' : 'none');
  }
}

/**
 * The cadastral overlay's tiles carry the City's road names and civic numbers from zoom 14,
 * so while it is on, the basemap's own road names stop at that zoom instead of drawing the
 * same street twice (2026-09-08 backlog note: on the raster this needed a basemap swap; here
 * it is a zoom range on the layers that carry names). `capAtZoom` null lifts the cap.
 */
export function capRoadNames(glMap, capAtZoom) {
  const style = glMap.getStyle();
  for (const id of metaList(style, 'cfr:road-name-layers')) {
    const layer = glMap.getLayer(id);
    if (!layer) continue;
    glMap.setLayerZoomRange(id, layer.minzoom ?? 0, capAtZoom == null ? 24 : capAtZoom);
  }
}
