# cfr_dispatch/config/__init__.py
# Stable API for CFR Dispatch configurations

from .paths import (
    BASE_DIR,
    VOCAB_DIR,
    SHAPES_DIR
)

from .models import (
    DispatchData
)

from .hardware import (
    AUDIO_SAMPLE_RATE,
    DEVICE_ID,
    resolve_audio_device
)

from .dsp import (
    NOISE_AMPLITUDE_THRESHOLD,
    NOISE_AMPLITUDE_THRESHOLD_MIN,
    SUSTAINED_LOUDNESS_WINDOW,
    SUSTAINED_LOUDNESS_CHUNKS_REQUIRED,
    TONE_ANALYSIS_DURATION_SECONDS,
    MAX_DISPATCH_DURATION_S,
    END_OF_DISPATCH_SILENCE_S,
    END_OF_DISPATCH_RMS_THRESHOLD,
    POST_EVENT_RESET_SILENCE_S,
    PHASE_1_CHECK_INTERVAL_S,
    MIN_PHASE_1_DURATION_S,
    MATCH_THRESHOLD_PERCENT,
    FREQUENCY_TOLERANCE_HZ,
    NUM_PEAKS_TO_FIND,
    TONE_ZSCORE_THRESHOLD,
    GOLDEN_FINGERPRINTS
)

from .vocab import (
    UNITS_VOCAB_RAW,
    RESPONSE_TYPES,
    RADIO_CHANNELS,
    MAP_GRIDS,
    CALL_TYPES,
    UNITS_VOCABULARY,
    UNIT_PARSING_IGNORE_LIST,
    INVALID_NEXT_WORDS
)

from .cloud import (
    STT_ENGINE,
    WHISPER_MODEL,
    INTEGRATION_PAYLOAD_OPTION,
    ENABLE_GOOGLE_MAPS_FALLBACK,
    ENABLE_NTFY_PUSH,
    USE_INTELLIGENT_PARSER,
    ADDRESS_SHAPEFILE_PATH,
    ZONES_SHAPEFILE_PATH,
    ADDRESS_FULL_ADDR_COLUMN,
    ADDRESS_HOUSE_NUM_COLUMN,
    ADDRESS_STREET_NAME_COLUMN,
    ADDRESS_STREET_TYPE_COLUMN,
    ZONES_MAP_NAME_COLUMN,
    ADDRESS_CONFIDENCE_THRESHOLD,
    STREET_NAME_CONFIDENCE_THRESHOLD,
    GCP_PROJECT_ID,
    RECOGNIZER_RESOURCE_NAME,
    STREET_NAMES_BASE_ID,
    MAP_GRIDS_ID,
    UNITS_ID,
    CALL_TYPES_ID,
    CHANNELS_ID,
    KEYWORDS_ID,
    NUM_STREET_CHUNKS,
    ADAPTATION_RESOURCE_IDS,
    BOOST_MAPPING,
    VERBOSITY_LEVEL
)

__all__ = [
    # Paths
    'BASE_DIR',
    'VOCAB_DIR',
    'SHAPES_DIR',
    # Models
    'DispatchData',
    # Hardware
    'AUDIO_SAMPLE_RATE',
    'DEVICE_ID',
    # DSP
    'NOISE_AMPLITUDE_THRESHOLD',
    'NOISE_AMPLITUDE_THRESHOLD_MIN',
    'SUSTAINED_LOUDNESS_WINDOW',
    'SUSTAINED_LOUDNESS_CHUNKS_REQUIRED',
    'TONE_ANALYSIS_DURATION_SECONDS',
    'MAX_DISPATCH_DURATION_S',
    'END_OF_DISPATCH_SILENCE_S',
    'END_OF_DISPATCH_RMS_THRESHOLD',
    'POST_EVENT_RESET_SILENCE_S',
    'PHASE_1_CHECK_INTERVAL_S',
    'MIN_PHASE_1_DURATION_S',
    'MATCH_THRESHOLD_PERCENT',
    'FREQUENCY_TOLERANCE_HZ',
    'NUM_PEAKS_TO_FIND',
    'TONE_ZSCORE_THRESHOLD',
    'GOLDEN_FINGERPRINTS',
    # Vocab
    'UNITS_VOCAB_RAW',
    'RESPONSE_TYPES',
    'RADIO_CHANNELS',
    'MAP_GRIDS',
    'CALL_TYPES',
    'UNITS_VOCABULARY',
    'UNIT_PARSING_IGNORE_LIST',
    'INVALID_NEXT_WORDS',
    # Cloud / Integration / GIS
    'STT_ENGINE',
    'WHISPER_MODEL',
    'INTEGRATION_PAYLOAD_OPTION',
    'ENABLE_GOOGLE_MAPS_FALLBACK',
    'ENABLE_NTFY_PUSH',
    'USE_INTELLIGENT_PARSER',
    'ADDRESS_SHAPEFILE_PATH',
    'ZONES_SHAPEFILE_PATH',
    'ADDRESS_FULL_ADDR_COLUMN',
    'ADDRESS_HOUSE_NUM_COLUMN',
    'ADDRESS_STREET_NAME_COLUMN',
    'ADDRESS_STREET_TYPE_COLUMN',
    'ZONES_MAP_NAME_COLUMN',
    'ADDRESS_CONFIDENCE_THRESHOLD',
    'STREET_NAME_CONFIDENCE_THRESHOLD',
    'GCP_PROJECT_ID',
    'RECOGNIZER_RESOURCE_NAME',
    'STREET_NAMES_BASE_ID',
    'MAP_GRIDS_ID',
    'UNITS_ID',
    'CALL_TYPES_ID',
    'CHANNELS_ID',
    'KEYWORDS_ID',
    'NUM_STREET_CHUNKS',
    'ADAPTATION_RESOURCE_IDS',
    'BOOST_MAPPING',
    'VERBOSITY_LEVEL'
]
