# Mosquitto MQTT Broker Configuration for CFR Dispatch System

# Default TCP Listener for Python / Backend Services
listener 1883
allow_anonymous true

# WebSockets Listener for React / Browser Kiosks
listener 9001
protocol websockets
allow_anonymous true

# Log configuration
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
